basic-settings:
    name: 'KingX'
    token: 'NTE3MzE4NTI4NjU5ODgxOTk1.DuAeEQ.gWLzJbjrqLyCBqeSZM5sSwNctYw'
    prefix: '-'
    server: '420676267004919818'
    ops:
    - '145064570237485056'
    embed-colour: '#fbae1d'
    game-status: 'KingX'
database:
    host: ''
    port: ''
    name: ''
    user: ''
    pass: ''
more-settings:
    error-length: 600
    autorole-enabled: true
staff-ratings:
    enabled: true
    staff-role: 'Mod'
    channels: [498286486718775327'420676267004919820]
